# Generated by Django 2.1.2 on 2019-03-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pH', models.DecimalField(decimal_places=1, max_digits=1)),
                ('CO2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('EC', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
