# Generated by Django 2.1.4 on 2019-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Temp',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='CO2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='EC',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pH',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
