# Generated by Django 2.1.7 on 2019-03-16 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor', '0004_sensor_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='CO2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='EC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pH',
            field=models.FloatField(),
        ),
    ]
