# Generated by Django 2.1.7 on 2019-04-05 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor', '0005_auto_20190316_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH_low_threshold', models.FloatField()),
                ('Temp_low_threshold', models.IntegerField()),
                ('CO2_low_threshold', models.FloatField()),
                ('EC_low_threshold', models.FloatField()),
                ('pH_high_threshold', models.FloatField()),
                ('Temp_high_threshold', models.IntegerField()),
                ('CO2_high_threshold', models.FloatField()),
                ('EC_high_threshold', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 23, 5, 45, 510414, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='sensor',
            name='system',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='sensor.System'),
        ),
    ]
